### PR TITLE
Issue #1: Update Day-1.md to add introduction and link to socials 

### LINKED ISSUE #1: Update DAY-1.md
@Vyom-Yadav Please add your introduction and links to your socials. Also, in the future, if you write a blog on your journey then you can share the link in the file.

### PR DESCRIPTION
**Pull request by Vyom-Yadav**
Resolves #1

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
Can we do it like, by telling every GSoCer to create an issue and a PR for them and see your PR as an example?

**Comment by Vyom-Yadav** [comment]
> Can we do it like, tell every GSoCer to create an issue and a PR for them and see your PR as an example?

Yeah sure, we can do that.

**Comment by Rahulkhinchi03** [comment]
Or should we create issues and assign them? What do you think?

**Comment by Vyom-Yadav** [comment]
> Or should we create issues and assign them? What do you think?

We can create issues and assign it to them, that would be better for them.

**Pull request merged**
