### PR TITLE
Update Schedule.md

### LINKED ISSUE #5: Host For the Podcast

### PR DESCRIPTION
**Pull request by rishabh0906**
Host for fossology podcast
Host issue link : https://github.com/DeCodeCafe/OpenSource-Cafe/issues/12

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@rishabh0906 Are you sure about the timing and date?

**Comment by rishabh0906** [comment]
yeah !!

**Comment by Rahulkhinchi03** [comment]
Please create one more issue for your Speaker and paste the link into the issue section.
Example: https://github.com/DeCodeCafe/OpenSource-Cafe/issues/1

Once done, ping the speaker on LinkedIn and tell them to make a PR on your issue.

**Comment by Rahulkhinchi03** [comment]
@rishabh0906 Please mention your host Issue link in the PR description.

**Comment by rishabh0906** [comment]
Host issue link : https://github.com/DeCodeCafe/OpenSource-Cafe/issues/12

**Pull request merged**
