### PR TITLE
Schedule Updated

### PR DESCRIPTION
**Pull request by Subhradeep10**

### CODE REVIEW

**Comment by Rahulkhinchi03** [comment]
@Subhradeep10 If you don't mind, Can I take the position of host for Aman Raj and Sumana Basu?

**Comment by Subhradeep10** [comment]
@Rahulkhinchi03 I already told them, I will be the host...Anyway no issue..you can take

**Comment by Rahulkhinchi03** [comment]
Actually, I wanted to have a conversation with a female so that I can ask questions related to women in tech and more. Please let me know if you can provide me with any 1 position.

**Comment by Subhradeep10** [comment]
@Rahulkhinchi03 Yeah , you can take it..no issue 
Or can we together host the event?

**Comment by Rahulkhinchi03** [comment]
@Subhradeep10  Please resolve merge conflict and remove your name from June 2

**Comment by Vyom-Yadav** [comment]
Closed, we already have conducted the event for 2nd June.

**Pull request closed without merging**
